[package]
name = "perpetual"
version = "0.4.1"
edition = "2021"
authors = ["Mutlu Simsek <msimsek@perpetual-ml.com>"]
homepage = "https://perpetual-ml.com"
description = "A self-generalizing gradient boosting machine which doesn't need hyperparameter optimization"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/perpetual-ml/perpetual"

keywords = ["machine-learning", "perpetual", "ai", "ml"]
categories = ["algorithms", "mathematics", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = 'fat'
codegen-units = 1
#debug = true      # due to flamegraph
#strip = false     # due to flamegraph

[dependencies]
rayon = "1.8"
thiserror = "1.0"
serde_json = { version = "1.0.128", features = ["float_roundtrip"] }
serde = { version = "1.0.210", features = ["derive"] }
approx = "0.5"
log = "0.4"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5"
polars = "0.41"
reqwest = { version = "0.12", features = ["blocking"] }
csv = "1.3"
chrono = "0.4"

[[bench]]
name = "perpetual_benchmarks"
harness = false
