name: docs
on: [pull_request, push]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          cp README.md python-package/README.md
          cp LICENSE python-package/LICENSE
      - run: pip install mkdocs-material
      - run: |
          cd python-package
          pip install .[dev]
          mkdocs gh-deploy --force
